services:
  mock-server:
    image: node:18-alpine
    container_name: mock-server
    ports:
      - "3000:3000"
    volumes:
      - ./data.json:/data/data.json
    working_dir: /data
    command: sh -c "npm install -g json-server && json-server --watch data.json --host 0.0.0.0"